version: '3'

services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.17.0
    volumes:
    - nexus-data:/nexus-data
    - /etc/localtime:/etc/localtime
    ports:
    - "8081:8081"
    restart: always

  nginx:
    container_name: nexus-nginx
    image: nginx:1.17.0-alpine
    volumes:
    - /etc/localtime:/etc/localtime
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8082:80"
    restart: always

volumes:
  nexus-data: {}
