version: '3'
services:
  php_fpm:
    container_name: php_fpm
    hostname: php_fpm
    image: lework/php-fpm:7.1.24-fpm-alpine3.8
    network_mode: docker
    privileged: true
    volumes:
      - "/Microservices:/Microservices"
    ports:
      - "9000:9000"
    dns:
      - 172.16.134.93
    restart: always
