version: '3'

services:
  maven:
    container_name: maven
    image: maven:3.6.1-jdk-8-slim
    volumes:
    - /etc/localtime:/etc/localtime
    - ./settings.xml:/usr/share/maven/conf/settings.xml
    - "./m2-repository:/tmp/.m2/repository"
