version: '3.2'

volumes:
  prometheus_data: {}
  alertmanager_data: {}
  grafana_data: {}

networks:
  monitor:

services:
  prometheus:
    image: prom/prometheus:v2.10.0
    container_name: prometheus
    hostname: prometheus
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - prometheus_data:/prometheus
      - ./prometheus/etc:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus-gateway.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=180d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitor
    restart: always

  node-exporter:
    image: prom/node-exporter:v0.18.0
    container_name: node-exporter
    hostname: node-exporter
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - monitor
    restart: always

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.16.0
    container_name: blackbox
    hostname: blackbox
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9115:9115"
    networks:
      - monitor
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.17.0
    container_name: alertmanager
    hostname: alertmanager
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - alertmanager_data:/alertmanager
      - ./alertmanager/etc:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      - monitor
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitor
  
  pushgateway:
    image: prom/pushgateway:v1.1.0 
    container_name: pushgateway
    hostname: pushgateway
    restart: always
    ports:
      - 9091:9091
    networks:
      - monitor

  pushclient:
    image: centos
    container_name: pushclient
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./pushclient/process-top.sh:/process-top.sh
    entrypoint: /process-top.sh
    restart: always
    pid: host 
    network_mode: service:pushgateway 
