version: '3'

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.16.0
    container_name: prometheus
    hostname: prometheus
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - prometheus_data:/prometheus
      - ./prometheus/etc/prometheus-influxdb.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: always

  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    hostname: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true 
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_DB=prometheus
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=${INFLUXDB_USER:-prometheus}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-prompass}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./influxdb_data:/var/lib/influxdb:rw
    ports:
      - 8086:8086
    restart: always
