---
version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    environment:
      TZ: 'Asia/Shanghai'
      - GITLAB_PAGES_ENABLED=true
      - GITLAB_PAGES_PORT=18080
      - GITLAB_PAGES_EXTERNAL_HTTP=:18080
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.77.130:10080'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        # email setting
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "my.email@gmail.com"
        gitlab_rails['smtp_password'] = "my-gmail-password"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
    ports:
      - '10080:10080'
      - '10443:443'
      - '10022:22'
    volumes:
      - ./gitlab_config:/etc/gitlab
      - ./gitlab_logs:/var/log/gitlab
      - ./gitlab_data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro
    restart: always

  runner:
    image: gitlab/gitlab-runner:latest
    depends_on:
      - "gitlab"
    volumes:
      - ./gitlab_runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/localtime:/etc/localtime:ro
    restart: always


# docker exec -it gitlab_runner_1 gitlab-runner register -n -r $REGISTRATION_TOKEN -u http://gitlab:10080 --executor docker --docker-image docker:latest --docker-network-mode gitlab_default  --docker-volumes "/var/run/docker.sock:/var/run/docker.sock"
