version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:3.4
    volumes:
      - "./mongo_data:/data"
      - "/etc/localtime:/etc/localtime"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456