version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:1.21.0
    volumes:
      - ./portainer_data:/data
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart: always
