version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - "./mysql_data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456