version: '3'

services:
  m3db:
    image: quay.io/m3db/m3dbnode:latest
    container_name: m3db
    hostname: m3db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./m3db_data:/var/lib/m3db
    cap_add:
      - SYS_RESOURCE
    ports:
      - 7201:7201
      - 7203:7203
      - 9003:9003 
    restart: always