version: '3'

services:
  openresty:
    container_name: openresty
    hostname: openresty
    image: openresty/openresty:centos
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./logs:/usr/local/openresty/nginx/logs"
      - "./html:/usr/local/openresty/nginx/html"
      - "./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./conf/conf.d:/usr/local/openresty/nginx/conf/conf.d"
      - /etc/localtime:/etc/localtime:ro
    restart: always