version: '3'
services:
  redis:
    container_name: redis-single
    image: redis:5.0.7
    volumes:
      - "./redis_single_data:/data"
      - "/etc/localtime:/etc/localtime"
    ports:
      - "6379:6379"
    restart: always
    command: [
      '--port 6379',
      '--requirepass 123456',
      '--maxclients 1000',
      '--maxmemory 256mb',
      '--maxmemory-policy volatile-ttl',
      '--appendonly yes',
      '--aof-use-rdb-preamble yes' 
    ]